name: nutri_scan
description: A modern calorie and nutrition tracker.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # For making HTTP requests to food APIs
  http: ^1.2.1

  # Barcode scanning
  mobile_scanner: ^5.1.1

  # For charts and graphs
  fl_chart: ^0.68.0

  # Optional: For Recipe Scanner (OCR)
  # google_ml_kit_text_recognition: ^0.11.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
